# -*- sh -*-
# shellcheck shell=bash
# shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

declare tarball_ext='tar.gz' # modify as needed

declare compiling=0

if (( compiling )) ; then
    :
else
    declare hardware
    hardware=$(uname -m)
    BUILD_OSS_SOURCE_TARBALL_ROOT="shellcheck-v0.11.0.linux.${hardware}"
    cmd-echo --id build-oss.conf "BUILD_OSS_SOURCE_TARBALL_ROOT redefined as '$BUILD_OSS_SOURCE_TARBALL_ROOT'."
    export BUILD_OSS_SOURCE_TARBALL_ROOT

    BUILD_OSS_SOURCE_TARBALL=${BUILD_OSS_SOURCE_TARBALL_ROOT}.$tarball_ext
    export BUILD_OSS_SOURCE_TARBALL

    BUILD_OSS_REMOTE_URL="https://github.com/koalaman/shellcheck/releases/download/v${BUILD_OSS_VERSION}/${BUILD_OSS_SOURCE_TARBALL}"
fi

cmd-echo --id "$ceid" "BUILD_OSS_SOURCE_DIR redefined as 'shellcheck-v0.11.0'."
BUILD_OSS_SOURCE_DIR='shellcheck-v0.11.0'
export BUILD_OSS_SOURCE_DIR

BUILD_OSS_ROOT="/opt/mop/build/oss"
export BUILD_OSS_ROOT

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    # PWD will be $BUILD_OSS_DIR
    # BUILD_OSS_ROOT=/opt/mop/build/oss
    # BUILD_OSS_SOFTWARE=shellcheck
    # BUILD_OSS_VERSION=0.11.0
    # BUILD_OSS_DIR=/opt/mop/build/oss/shellcheck/0.11.0
    : # dummy statement to placate shellcheck until real statements are added
    wget "$BUILD_OSS_REMOTE_URL"
}

build-oss-unpack () {
    if ! tar -xf "$BUILD_OSS_SOURCE_TARBALL"; then
        false; exit;
    fi
}

build-oss-install () {
    cp -v shellcheck "$OPTBIN"
}

build-oss-coda () {
    cmd-echo --id "$ceid" --infoc \
             "build-oss of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
    if (( compiling )) ; then
        # shellcheck disable=SC2016 #https://github.com/koalaman/shellcheck/wiki/SC2016
        cmd-echo --id "$ceid" --infoc \
             'Do not forget to add "$HOME/.cabal/bin" to your $PATH.'
    fi
}
