# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

# Documentation purposes:
# BUILD_OSS_ROOT=/opt/mop/build/oss
# PWD will be $BUILD_OSS_DIR
BUILD_OSS_DIR=/opt/mop/build/oss/shellcheck/0.11.0
BUILD_OSS_SOFTWARE=shellcheck
BUILD_OSS_VERSION=0.11.0
BUILD_OSS_SOURCE_DIR=shellcheck-0.11.0
BUILD_OSS_SOURCE_DIR="${BUILD_OSS_SOFTWARE}-v${BUILD_OSS_VERSION}"
build-oss-ce "BUILD_OSS_SOURCE_DIR redefined $BUILD_OSS_SOURCE_DIR"
BUILD_OSS_TARBALL_ROOT=shellcheck-0.11.0
declare hardware
hardware=$(uname -m)
BUILD_OSS_TARBALL_ROOT="${BUILD_OSS_SOFTWARE}-v${BUILD_OSS_VERSION}.linux.${hardware}"
build-oss-ce "BUILD_OSS_TARBALL_ROOT redefined as '$BUILD_OSS_TARBALL_ROOT'."

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_TARBALL=${BUILD_OSS_TARBALL_ROOT}.$tarball_ext

BUILD_OSS_URL="https://github.com/koalaman/shellcheck/releases/download/v${BUILD_OSS_VERSION}/${BUILD_OSS_TARBALL}"

BUILD_OSS_TIMESTAMP="${BUILD_OSS_DIR}/build-oss.timestamp"

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    if [[ ! -f $BUILD_OSS_TARBALL ]]; then
        # Pick one
        wget "$BUILD_OSS_URL"
    else
        build-oss-ce "Tarball $BUILD_OSS_TARBALL exists."
    fi
}

build-oss-unpack () {
    if [[ -d $BUILD_OSS_SOURCE_DIR ]]; then
         build-oss-ce "Tarball  already expanded."
    elif ! tar -xf "$BUILD_OSS_TARBALL"; then
        false; exit;
    fi
}

build-oss-install () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        cp -v shellcheck "$OPTBIN"
    else
        build-oss-ce "shellcheck already installed"
    fi
}

build-oss-coda () {
    build-oss-ce --infoc \
                 "build/install of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
    date +%s > "${BUILD_OSS_TIMESTAMP}"
}
