# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_SOURCE_TARBALL=${BUILD_OSS_SOURCE_TARBALL_ROOT}.$tarball_ext
export BUILD_OSS_SOURCE_TARBALL

BUILD_OSS_ROOT="/opt/mop/build/oss"
export BUILD_OSS_ROOT

# Enhance or remove these functions as needed.

build-oss-get () {
# Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    # PWD will be $BUILD_OSS_DIR
    # BUILD_OSS_ROOT=/opt/mop/build/oss
    # BUILD_OSS_SOFTWARE=libtool
    # BUILD_OSS_VERSION=2.5.4
    # BUILD_OSS_DIR=/opt/mop/build/oss/libtool/2.5.4
    # BUILD_OSS_SOURCE_DIR=libtool-2.5.4
    # BUILD_OSS_SOURCE_TARBALL_ROOT=libtool-2.5.4
    : # dummy statement to placate shellcheck until real statements are added
    wget --verbose https://ftpmirror.gnu.org/libtool/libtool-2.5.4.tar.gz
}

build-oss-unpack () {
    set -x
    if [[ -n $tarball_ext ]]; then
        if ! tar zxf "$BUILD_OSS_SOURCE_TARBALL"; then
            false; exit;
        fi
    else
        cmd-echo --id "build-oss" "No tarball. Downloaded binary."
    fi
    set +x
}

build-oss-configure () {
    ./configure
}

build-oss-build () {
    make
}

build-oss-test () {
    true; return
}

build-oss-install () {
    make install
}

build-oss-coda () {
    # shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154
    cmd-echo --id "$ceid" "build-oss of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
}
