# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_SOURCE_TARBALL=${BUILD_OSS_SOURCE_TARBALL_ROOT}.$tarball_ext
export BUILD_OSS_SOURCE_TARBALL

BUILD_OSS_ROOT="/opt/mop/build/oss"
export BUILD_OSS_ROOT

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    # PWD will be $BUILD_OSS_DIR
    # BUILD_OSS_ROOT=/opt/mop/build/oss
    # BUILD_OSS_SOFTWARE=xnedit
    # BUILD_OSS_VERSION=1.6.3
    # BUILD_OSS_DIR=/opt/mop/build/oss/xnedit/1.6.3
    # BUILD_OSS_SOURCE_DIR=xnedit-1.6.3
    # BUILD_OSS_SOURCE_TARBALL_ROOT=xnedit-1.6.3
    # BUILD_OSS_SOURCE_TARBALL=xnedit-1.6.3.tar.gz
    curl -L https://github.com/unixwork/xnedit/releases/download/v1.6.3/xnedit-1.6.3.tar.gz -o xnedit-1.6.3.tar.gz
}

build-oss-unpack () {
    if [[ -n $tarball_ext ]]; then
        if ! tar zxf "$BUILD_OSS_SOURCE_TARBALL"; then
            false; exit;
        fi
    else
        cmd-echo --id "build-oss" "No tarball. Downloaded binary."
    fi
}

build-oss-build () {
    make
}

build-oss-install () {
    sudo make install
}

build-oss-coda () {
    # shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154
    cmd-echo --id "$ceid" "build-oss of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
}
