# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

# Documentation purposes:
# BUILD_OSS_ROOT=/opt/mop/build/oss
# PWD will be $BUILD_OSS_DIR
BUILD_OSS_DIR=/opt/mop/build/oss/emacs/30.2
BUILD_OSS_SOFTWARE=emacs
BUILD_OSS_VERSION=30.2
BUILD_OSS_SOURCE_DIR=emacs-30.2
BUILD_OSS_TARBALL_ROOT=emacs-30.2

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_TARBALL=${BUILD_OSS_TARBALL_ROOT}.$tarball_ext

BUILD_OSS_URL="https://ftpmirror.gnu.org/emacs/$BUILD_OSS_TARBALL"

BUILD_OSS_TIMESTAMP="${BUILD_OSS_DIR}/build-oss.timestamp"

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    if [[ ! -f $BUILD_OSS_TARBALL ]]; then
        wget "$BUILD_OSS_URL"
    else
        build-oss-ce "Tarball $BUILD_OSS_TARBALL exists."
    fi
}

build-oss-unpack () {
    if [[ -d $BUILD_OSS_SOURCE_DIR ]]; then
         build-oss-ce "Tarball $BUILD_OSS_TARBALL already expanded."
    elif ! tar -xf "$BUILD_OSS_TARBALL"; then
        false; exit;
    fi
}

build-oss-configure () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
                (
            set -e
            build-oss-ce -f "Installing support libraries..."
            sudo apt-get install -y libgccjit-"${GCC_VERSION}"* libgccjit0
            sudo apt-get install -y \
                 gcc-"${GCC_VERSION}" \
                 build-essential

            sudo apt-get install -y \
                 libacl1-dev \
                 libcairo2-dev \
                 libgif-dev \
                 libgnutls28-dev \
                 libgtk-3-dev \
                 libharfbuzz-dev \
                 libncurses-dev \
                 libtiff-dev \
                 libtree-sitter-dev \
                 libxaw3dxft6t64 \
                 libxaw3dxft8 \
                 libxaw7-dev \
                 texinfo \
                 xattr \
                 xaw3dg

            # Configure
            build-oss-ce -f "Running ./configure.."
            ./configure \
                --prefix="$OPTROOT" \
                --with-native-compilation \
                --with-pgtk \
                --without-selinux \
                --without-gsettings \
                --with-modules \
                --with-tree-sitter
        )
    else
        build-oss-ce "./configure has already run"
    fi
}

build-oss-build () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        make
    else
        build-oss-ce "make has already run"
    fi
}

build-oss-test () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
	    make test
    else
        build-oss-ce "make test has already run"
    fi
}

build-oss-install () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        make install
    else
        build-oss-ce "make install has already run"
    fi
}

build-oss-coda () {
    build-oss-ce --infoc \
                 "build/install of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
    date +%s > "${BUILD_OSS_TIMESTAMP}"
}

