# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

declare tarball_ext='tar.xz' # modify as needed
BUILD_OSS_SOURCE_TARBALL=${BUILD_OSS_SOURCE_TARBALL_ROOT}.$tarball_ext
export BUILD_OSS_SOURCE_TARBALL

BUILD_OSS_ROOT="/opt/mop/build/oss"
export BUILD_OSS_ROOT

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    # PWD will be $BUILD_OSS_DIR
    # BUILD_OSS_ROOT=/opt/mop/build/oss
    # BUILD_OSS_SOFTWARE=emacs
    # BUILD_OSS_VERSION=30.2
    # BUILD_OSS_DIR=/opt/mop/build/oss/emacs/30.2
    # BUILD_OSS_SOURCE_DIR=emacs-30.2
    # BUILD_OSS_SOURCE_TARBALL_ROOT=emacs-30.2
    : # dummy statement to placate shellcheck until real statements are added
    wget https://ftpmirror.gnu.org/emacs/emacs-30.2.tar.xz
}

build-oss-unpack () {
    if ! tar -xf "$BUILD_OSS_SOURCE_TARBALL"; then
        false; exit;
    fi
}

build-oss-configure () {
    # Get related libs
    # shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154
    cmd-echo --id "$ceid" "Installing support libraries..."
    sudo apt-get install -y libgccjit-"${GCC_VERSION}"* libgccjit0
    sudo apt-get install -y \
         gcc-"${GCC_VERSION}" \
         build-essential

    sudo apt-get install -y \
         libharfbuzz-dev \
         libxaw7-dev \
         libgif-dev \
         libtiff-dev \
         libgnutls28-dev \
         libtree-sitter-dev \
         libncurses-dev \
         texinfo \
         libcairo2-dev \
         libacl1-dev \
         xattr \
         xaw3dg \
         libxaw3dxft8 \
         libxaw3dxft6t64

    # Configure
    cmd-echo --id "$ceid" "Running ./configure.."
    ./configure \
        --prefix=/opt/mop \
        --with-native-compilation \
        --with-x-toolkit=lucid \
        --without-selinux \
        --without-gsettings \
        --with-modules \
        --with-tree-sitter
}

build-oss-build () {
    make
}

build-oss-test () {
    make test
}

build-oss-install () {
    make install
}

build-oss-coda () {
    # shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154
    cmd-echo --id "$ceid" "build-oss of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
}
