# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

# Documentation purposes:
# BUILD_OSS_ROOT=/opt/mop/build/oss
# PWD will be $BUILD_OSS_DIR
BUILD_OSS_DIR=/opt/mop/build/oss/tailscale/any
BUILD_OSS_SOFTWARE=tailscale
BUILD_OSS_VERSION=any
# shellcheck disable=SC2034 #https://github.com/koalaman/shellcheck/wiki/SC2034
BUILD_OSS_SOURCE_DIR=$BUILD_OSS_DIR
BUILD_OSS_INSTALL_SCRIPT=tailscale-install

BUILD_OSS_URL="https://tailscale.com/install.sh"

BUILD_OSS_TIMESTAMP="${BUILD_OSS_DIR}/build-oss.timestamp"

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    if [[ ! -f $BUILD_OSS_TARBALL ]]; then
        # Pick one
        curl -o "$BUILD_OSS_INSTALL_SCRIPT" -fsSL "$BUILD_OSS_URL"
    else
        build-oss-ce "Tarball $BUILD_OSS_TARBALL exists."
    fi
}

build-oss-install () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        sh "$BUILD_OSS_INSTALL_SCRIPT"
    else
        build-oss-ce "install has already run"
    fi
}

build-oss-coda () {
    build-oss-ce --infoc \
                 "build/install of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."
    date +%s > "${BUILD_OSS_TIMESTAMP}"
}
