# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

# Documentation purposes:
# BUILD_OSS_ROOT=/opt/mop/build/oss
# PWD will be $BUILD_OSS_DIR
BUILD_OSS_DIR=/opt/mop/build/oss/ddd/3.4.1
BUILD_OSS_SOFTWARE=ddd
BUILD_OSS_VERSION=3.4.1
BUILD_OSS_SOURCE_DIR=ddd-3.4.1
BUILD_OSS_TARBALL_ROOT=ddd-3.4.1

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_TARBALL=${BUILD_OSS_TARBALL_ROOT}.$tarball_ext

BUILD_OSS_URL="ftp://ftp.gnu.org/gnu/$BUILD_OSS_SOFTWARE/$BUILD_OSS_TARBALL"

BUILD_OSS_TIMESTAMP="${BUILD_OSS_DIR}/build-oss.timestamp"

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    if [[ ! -f $BUILD_OSS_TARBALL ]]; then
        # Pick one
        wget "$BUILD_OSS_URL"
    else
        build-oss-ce "Tarball $BUILD_OSS_TARBALL exists."
    fi
}

build-oss-unpack () {
    if [[ -d $BUILD_OSS_SOURCE_DIR ]]; then
         build-oss-ce "Tarball $BUILD_OSS_TARBALL already expanded."
    elif ! tar -xf "$BUILD_OSS_TARBALL"; then
        false; exit;
    fi
}

build-oss-configure () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        cd .. || exit # We are in expanded tarball dir but ddd does not want us
                      # there initially. See doc/INSTALL for details.
        mkdir build
        cd build || exit
        "../$BUILD_OSS_SOURCE_DIR/configure" --prefix=/opt/mop
    else
        build-oss-ce "./configure has already run"
    fi
}

build-oss-build () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        make
    else
        build-oss-ce "make has already run"
    fi
}

build-oss-test () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
	    make check
    else
        build-oss-ce "make check has already run"
    fi
}

build-oss-install () {
    if [[ ! -r "${BUILD_OSS_TIMESTAMP}" ]] \
           || find . -type f -newer "${BUILD_OSS_TIMESTAMP}" -print -quit | grep -q . ; then
        make install
    else
        build-oss-ce "make install has already run"
    fi
}

build-oss-coda () {
    build-oss-ce --infoc \
                 "build/install of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete."\
                 "Run 'make clean' to remove the program binaries, libraries and" \
                 "                 object files from the source directory." \
                 "Run 'make distclean' to remove the Makefiles, the header files" \
                 "                     containing system-dependent definitions, and" \
                 "                     'config.status' (all the files that 'configure' created)."
    date +%s > "${BUILD_OSS_TIMESTAMP}"
}
