# -*- sh -*-
# shellcheck shell=bash

declare BUILD_OSS_CONF_FILE_API_VERSION=2
export BUILD_OSS_CONF_FILE_API_VERSION

declare tarball_ext='tar.gz' # modify as needed
BUILD_OSS_SOURCE_TARBALL=${BUILD_OSS_SOURCE_TARBALL_ROOT}.$tarball_ext
export BUILD_OSS_SOURCE_TARBALL

BUILD_OSS_ROOT="/opt/mop/build/oss"
export BUILD_OSS_ROOT

# Enhance or remove these functions as needed.

build-oss-get () {
    # Commands to get the tarball and write it to $BUILD_OSS_DIR
    # or to get a git repo.
    # PWD will be $BUILD_OSS_DIR
    # BUILD_OSS_ROOT=/opt/mop/build/oss
    # BUILD_OSS_SOFTWARE=ddd
    # BUILD_OSS_VERSION=3.4.1
    # BUILD_OSS_DIR=/opt/mop/build/oss/ddd/3.4.1
    # BUILD_OSS_SOURCE_DIR=ddd-3.4.1
    # BUILD_OSS_SOURCE_TARBALL_ROOT=ddd-3.4.1
    : # dummy statement to placate shellcheck until real statements are added
    if [[ ! -f ddd-3.4.1.tar.gz ]]; then
        wget ftp://ftp.gnu.org/gnu/ddd/ddd-3.4.1.tar.gz
    else
        cmd-echo --id "build_oss_get" "Tarball already exists. Not downloading."
    fi
}

build-oss-unpack () {
    if ! tar zxf "$BUILD_OSS_SOURCE_TARBALL"; then
        false; exit;
    fi
}

build-oss-configure () {
    cd .. || exit # We are in expanded tarball dir but ddd does not want us
                  # there initially. See doc/INSTALL for details.
    mkdir build
    cd build || exit
    "../$BUILD_OSS_SOURCE_DIR/configure" --prefix=/opt/mop
}

build-oss-build () {
    make
}

build-oss-test () {
    make check
}

build-oss-install () {
    make install
}

build-oss-coda () {
    # shellcheck disable=SC2154 #https://github.com/koalaman/shellcheck/wiki/SC2154
    cmd-echo --id "$ceid" "build-oss of $BUILD_OSS_SOFTWARE version $BUILD_OSS_VERSION is complete." \
             "Run 'make clean' to remove the program binaries, libraries and object files from the source directory." \
             "Run 'make distclean' to remove the Makefiles, the header files containing system-dependent" \
             "     definitions, and 'config.status' (all the files that 'configure' created)"
}
